name: Test Secret Upload
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Write secret to file
        run: echo "MY_SECRET=${{ secrets.ARTIFACT_SECRET }}" > secrets.txt

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-secrets-file
          path: secrets.txt
